version: '3.3'
services:
  mongodb:
    image: 'mongo:4.0'
    volumes:
      - 'mongodata:/etc/mongo'
    ports:
      - 27017:27017
  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
      - 33060:33060
    environment:
      MYSQL_ROOT_PASSWORD: example
volumes:
  esdata:
  mongodata:
